### ISSUE TITLE
Where is the implementation of CustomerRepository?

### ISSUE THREAD

**Issue by chenkan** [sdeleuze/spring-boot-kotlin-demo#1]
and how about `findByLastName` fun works?

Best wishes
ChenKan

**Comment by seadowg** [comment]
@chenkan Spring takes care of generating the implementation and injecting the implementation whenever you `@Autowired` it as a field or as part of a constructor. For `findByLastName` the behaviour will be inferred from the method name: If the repository is talking to a sql database it would execute a `select * from customers where lastName = ?` when it was called.

There is more info on this magic here: https://spring.io/guides/gs/accessing-data-jpa/. Does that answer your question?

**Comment by chenkan** [comment]
@seadowg Yes, thank you😄

> Spring takes care of generating the implementation and injecting the implementation whenever you @Autowired
