### ISSUE TITLE
where is the config file for datasource' properties

### ISSUE THREAD

**Issue by snaigle** [sdeleuze/spring-boot-kotlin-demo#2]
I can't find the config file for datasource's properties?

Best wishes!

**Comment by sdeleuze** [comment]
I guess you could use regular [Spring Boot properties](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) and specify them in https://github.com/sdeleuze/spring-boot-kotlin-demo/blob/master/src/main/resources/application.yml. Is that what you had in mind?

**Comment by mszarlinski** [comment]
In this case Spring Boot provides in-memory database with default settings using its auto-configuration mechanism: https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-auto-configuration.html

**Comment by sdeleuze** [comment]
Closing this issue which is more a question about typical Spring Boot behavior and has been answered.
