### ISSUE TITLE
Add /customers to GetMapping path in CustomerController

### ISSUE THREAD

**Issue by 58bits** [sdeleuze/spring-boot-kotlin-demo#4]
Thanks for this, and the great talk at https://www.infoq.com/presentations/servlet-reactive-stack

Minor suggestion. I used this as the starting point to experiment a little with Spring 2.0 and Kotlin, and was stuck for a bit trying to get anything from resources/static to load since "/" was already mapped to `CustomerController`. It might be helpful to update the routes in `CustomerController` as...

```
@RestController
class CustomerController(private val repository: CustomerRepository) {

	@GetMapping("/customers")
	fun findAll() = repository.findAll()

	@GetMapping("/customers/{lastName}")
	fun findByLastName(@PathVariable lastName:String)
			= repository.findByLastName(lastName)
}
```

Thanks again...

**Comment by sdeleuze** [comment]
You're welcome :-) I have taken in account your proposal.
